### PR TITLE
Add Cucumber support to enginex

### PR DESCRIPTION
**Pull request by radar**
This commit changes the test-framework option to test-frameworks to allow for a larger variety of test framework support. This commit uses this new option to allow users to specify what test frameworks out of test/unit, RSpec and Cucumber they would wish to use.

### CODE REVIEW

**Comment by ahawkins** [comment]
can you please merge this? I was going to do this today since I've already done it one of my gems.

**Comment by Spaceghost** [comment]
It would be great to have this added to enginex, I've been working with your book and am building my own engine and would love to be able to use both cucumber and rspec with enginex.

**Comment by ramontayag** [comment]
+1

**Comment by radar** [comment]
You guys could use is built in to rails plugin generator now to get this. I think that enginex should not be used

**Pull request closed without merging**
