### PR TITLE
use sqlite3 instead of sqlite3-ruby

### PR DESCRIPTION
**Pull request by etehtsea**
Minor improvement, but this eliminates annoying sqlite3-ruby warning.

### CODE REVIEW

**Comment by josevalim** [comment]
Sorry, which sqlite3-ruby warning?

**Comment by etehtsea** [comment]
#######################################################

Hello! The sqlite3-ruby gem has changed it's name to just sqlite3.  Rather than
installing `sqlite3-ruby`, you should install `sqlite3`.  Please update your
dependencies accordingly.

Thanks from the Ruby sqlite3 team!

<3 <3 <3 <3

#######################################################

**Comment by josevalim** [comment]
Ugh, i will let your pull request open, I need to check other things related to the book before applying it. Thanks!

**Comment by etehtsea** [comment]
Page 16? :)

**Comment by josevalim** [comment]
Applied and book changed, thanks!

**Pull request closed without merging**
